Improved installation script.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,8 +6,7 @@ CYAN='\033[1;36m'
 RED='\033[1;31m'
 RESET='\033[0m'
 
-spin()
-{
+spin() {
   while :
   do
     sleep 5
@@ -15,119 +14,152 @@ spin()
   done
 }
 
+installErplag () {
+	make
+
+	sudo cp erplag /usr/local/bin
+	stat=$?
+	if [ $stat -ne 0 ]
+	then
+		installErr 
+	fi
+
+	sudo cp .compiler /usr/local/bin
+	stat=$?
+	if [ $stat -ne 0 ]
+	then
+		installErr 
+	fi
+
+	sudo cp erpclr /usr/local/bin
+	stat=$?
+	if [ $stat -ne 0 ]
+	then
+		installErr 
+	fi
+
+	make clean	
+}
 
 installErr () {
 	printf "\n${BOLD}${RED}ERPLAG compiler installation failed. \nPlease export repository directory to PATH variable.${RESET}\n"
 	printf "Press enter to continue..."
 	read
+	
+	exit
 }
+
+success () {
+	printf "\n${BOLD}${GREEN}ERPLAG compiler has been successfully installed!${RESET}\n"
+	printf "Use ${BOLD}${CYAN}erplag -h ${RESET}to read the guidelines for using the compiler\n"
+	printf "\nPress enter to continue..."
+	read
+	
+	exit
+}
+
+###################################################################################################################################
 
 if [ -f /usr/local/bin/erplag ]
 then
 	printf "${BOLD}${GREEN}ERPLAG compiler is already installed in this system${RESET}\n\n" 
 	printf "Please use ${BOLD}${CYAN}./rebuild ${RESET}to quickly remake the compiler\n"
 	printf "Otherwise, use ${BOLD}${CYAN}./uninstall ${RESET} to uninstall the compiler\n"
-
 	exit
 fi
 
-sudo printf "Installing ERPLAG compiler... \n"
+sudo printf "Installing ERPLAG compiler... \n\n"
+missing=""
 
-
-if [[ "$OSTYPE" == "linux-gnu"* ]]
+which gcc >> /dev/null
+if [ $? -ne 0 ]
 then
-	if [ -f /etc/os-release ]; then
-	    # freedesktop.org and systemd
-	    . /etc/os-release
-	    OS=$NAME
-	    TYPE=$ID_LIKE
-	fi
-
-	if [[ "$TYPE" == "debian" ]] 
-	then
-		sudo apt-get update
-		sudo apt-get install build-essential
-		sudo apt-get install nasm
-	elif [[ "$TYPE" == "rhel fedora" ]] 
-	then
-		sudo yum install gcc
-		sudo yum install make
-		sudo yum install wget
-		wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/linux/nasm-2.14.02-0.fc27.x86_64.rpm
-		sudo yum install nasm-2.14.02-0.fc27.x86_64.rpm
-		rm -f nasm-2.14.02-0.fc27.x86_64.rpm
-	else
-		printf "${BOLD}${RED}ERPLAG installer could not identify the linux distribution to check the dependencies. Please install ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}and run the makefile in this repository. Subsequently, add this directory to the environment path variable${RESET}\n"
-		
-		exit
-	fi	
-elif [[ "$OSTYPE" == "darwin"* ]]
+	printf "${BOLD}${RED}Dependency : gcc is not installed in this system!\n${RESET}"
+	missing="gcc"
+fi
+which make >> /dev/null
+if [ $? -ne 0 ]
 then
-	var=$(sudo which brew) 
-	if test "$var" == ""
-	then
-		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-	fi
+	printf "${BOLD}${RED}Dependency : make is not installed in this system!\n${RESET}"
+	missing="${missing} make"
+fi
+which nasm >> /dev/null
+if [ $? -ne 0 ]
+then
+	printf "${BOLD}${RED}Dependency : nasm is not installed in this system!\n${RESET}"
+	missing="${missing} nasm"
+fi
 
-	spin &
-	SPIN_PID=$!
-	brew update
-	kill -9 $SPIN_PID
-	wait $SPIN_PID 2>/dev/null
-
-	spin &
-	SPIN_PID=$!
-	brew install gcc
-	kill -9 $SPIN_PID
-	wait $SPIN_PID 2>/dev/null
-
-	spin &
-	SPIN_PID=$!
-	brew install make
-	kill -9 $SPIN_PID
-	wait $SPIN_PID 2>/dev/null
-
-	spin &
-	SPIN_PID=$!
-	brew install nasm
-	kill -9 $SPIN_PID
-	wait $SPIN_PID 2>/dev/null
+if [[ "$missing" == "" ]]
+then
+	installErplag
+	success
 else
-    printf "${BOLD}${RED}ERPLAG compiler has not been designed for this OS. Please use a 64-bit linux distribution, macOS or Windows OS.${RESET}\n"
-    printf "Press enter to continue..."
-	read
-    exit
+	printf "${BOLD}${CYAN}Attempting to install missing packages...${RESET}\n"
+	
+	if [[ "$OSTYPE" == "linux-gnu"* ]]
+	then
+		which apt-get >> /dev/null
+		if [ $? -eq 0 ]
+		then
+			sudo apt-get update
+			sudo apt-get install -y $missing
+			
+			installErplag
+			success
+		fi
+		
+		which yum >> /dev/null
+		if [ $? -eq 0 ]
+		then
+			sudo yum -y install $missing
+			sudo yum -y install wget
+			
+			wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/linux/nasm-2.14.02-0.fc27.x86_64.rpm
+			sudo yum -y install nasm-2.14.02-0.fc27.x86_64.rpm
+			rm -f nasm-2.14.02-0.fc27.x86_64.rpm
+			
+			installErplag
+			success
+		fi
+		
+		
+		printf "${BOLD}${RED}\nInstaller could not identify the package manager in your linux distribution. Please install ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}and then run the installation script${RESET}\n"	
+		exit
+	elif [[ "$OSTYPE" == "darwin"* ]]
+	then
+		var=$(sudo which brew) 
+		if test "$var" == ""
+		then
+			printf "${BOLD}${RED}Please install Homebrew or ensure that ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}are installed before running the installaton script${RESET}\n" ;
+			exit
+		fi
+
+		spin &
+		SPIN_PID=$!
+		brew update
+		kill -9 $SPIN_PID
+		wait $SPIN_PID 2>/dev/null
+
+		spin &
+		SPIN_PID=$!
+		brew install gcc
+		kill -9 $SPIN_PID
+		wait $SPIN_PID 2>/dev/null
+
+		spin &
+		SPIN_PID=$!
+		brew install make
+		kill -9 $SPIN_PID
+		wait $SPIN_PID 2>/dev/null
+
+		spin &
+		SPIN_PID=$!
+		brew install nasm
+		kill -9 $SPIN_PID
+		wait $SPIN_PID 2>/dev/null
+	else
+		printf "${BOLD}${RED}Linux distribution could not be identified! Please install ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}and then run the installation script${RESET}\n"		
+		exit
+	fi
 fi
-
-make
-
-sudo cp erplag /usr/local/bin
-stat=$?
-if [ $stat -ne 0 ]
-then
-	installErr 
-	exit
-fi
-
-sudo cp .compiler /usr/local/bin
-stat=$?
-if [ $stat -ne 0 ]
-then
-	installErr 
-	exit
-fi
-
-sudo cp erpclr /usr/local/bin
-stat=$?
-if [ $stat -ne 0 ]
-then
-	installErr 
-	exit
-fi
-
-make clean
-
-printf "\n${BOLD}${GREEN}ERPLAG compiler has been successfully installed!${RESET}\n"
-printf "Use ${BOLD}${CYAN}erplag -h ${RESET}to read the guidelines for using the compiler\n"
-printf "\nPress enter to continue..."
-read
