Added proper exit codes to script files

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,8 +16,13 @@ spin() {
 
 installErplag () {
 	make
+	if [ $? -ne 0 ]
+	then
+		printf "\n${BOLD}${RED}ERPLAG compiler installation failed! Please check the source code for errors\n${RESET}"
+		exit 1
+	fi
 
-    	sudo cp .compiler /usr/local/bin
+    sudo cp .compiler /usr/local/bin
 	sudo cp erplag /usr/local/bin
 	sudo cp erpclr /usr/local/bin
 
@@ -30,7 +35,7 @@ success () {
 	printf "\nPress enter to continue..."
 	read
 	
-	exit
+	exit 0
 }
 
 ###################################################################################################################################
@@ -40,7 +45,7 @@ then
 	printf "${BOLD}${GREEN}ERPLAG compiler is already installed in this system${RESET}\n\n" 
 	printf "Please use ${BOLD}${CYAN}./rebuild ${RESET}to quickly remake the compiler\n"
 	printf "Otherwise, use ${BOLD}${CYAN}./uninstall ${RESET} to uninstall the compiler\n"
-	exit
+	exit 1
 fi
 
 sudo printf "Installing ERPLAG compiler... \n\n"
@@ -139,14 +144,14 @@ else
 		fi
 		
 		printf "${BOLD}${RED}\nInstaller could not identify the package manager in your linux distribution. Please install ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}and then run the installation script${RESET}\n"	
-		exit
+		exit 1
 	elif [[ "$OSTYPE" == "darwin"* ]]
 	then
 		var=$(sudo which brew) 
 		if test "$var" == ""
 		then
 			printf "${BOLD}${RED}Please install Homebrew or ensure that ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}are installed before running the installaton script${RESET}\n" ;
-			exit
+			exit 1
 		fi
 
 		spin &
@@ -174,6 +179,6 @@ else
 		wait $SPIN_PID 2>/dev/null
 	else
 		printf "${BOLD}${RED}Linux distribution could not be identified! Please install ${CYAN}gcc, make, ${RED}and ${CYAN}nasm ${RED}and then run the installation script${RESET}\n"		
-		exit
+		exit 1
 	fi
 fi
diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -21,7 +21,7 @@ input () {
 			return
 		elif  [ "$ans" = "n" -o "$ans" = "N" ]
 		then
-			exit
+			exit 0
 		else
 			printf "\n${BOLD}${MAGENTA}Please re-enter correct option ${RESET}(y/n) "
 		fi
@@ -33,14 +33,20 @@ then
 	printf "${BOLD}${MAGENTA}ERPLAG compiler is not installed!${RESET}\n" 
 	printf "Please install the compiler with ${BOLD}${CYAN}./install ${RESET}before using ${BOLD}${CYAN}./rebuild${RESET}\n"
 
-	exit
+	exit 1
 fi
 
 printf "${BOLD}${CYAN}Proceed with re-building ERPLAG compiler? ${RESET}(y/n) "
 input
 
 sudo printf "Rebuilding ERPLAG compiler...\n\n"
+
 make
+if [ $? -ne 0 ]
+then
+	printf "\n${BOLD}${RED}ERPLAG compiler re-build failed! Please check the errors above\n${RESET}"
+	exit 1
+fi
 
 sudo cp erplag /usr/local/bin
 sudo cp .compiler /usr/local/bin
